### ISSUE TITLE
Hook into build-figma-plugin's generated webpack config?

### ISSUE THREAD

**Issue by nickradford** [yuanqing/create-figma-plugin#10]
I'd like to use a react library along side the preact ui code, so I think I need to add some configuration to webpack in order to alias `react` and `react-dom` to `preact/compat`.

Is there a way to currently do this that I'm not seeing documented? Happy to implement and offer a PR if the feature doesn't exist.

**Comment by nickradford** [comment]
I'm dumb, sorry: https://github.com/yuanqing/create-figma-plugin/blob/master/docs/recipes/custom-webpack-configuration.md#readme

**Comment by nickradford** [comment]
I was able to achieve this by creating `figma-plugin.config.js` in my project root with content
```js
module.exports = function (config) {
  return {
    ...config,
    resolve: {
      ...config.resolve,
      alias: {
        ...config.resolve.alias,
        react: "preact/compat",
        "react-dom": "preact-compat",
      },
    },
  };
};
```

**Comment by devinhalladay** [comment]
Is this still possible?

**Comment by yuanqing** [comment]
@devinhalladay The API is slightly different now given the move to esbuild. See https://yuanqing.github.io/create-figma-plugin/#customizing-the-underlying-esbuild-configuration
