### ISSUE TITLE
Dropdown height doesn't update with dynamic items

### ISSUE THREAD

**Issue by sntiagomoreno** [yuanqing/create-figma-plugin#100]
I have a dropdown that's dynamically rendered and populated according to the user selection. It seems that the dropdown doesn't update it's height calculation until one option of the list is selected.

This is how the dropdown displays when opened for the first time:
<img width="297" alt="Screen Shot 2022-05-11 at 10 13 10 AM" src="https://user-images.githubusercontent.com/10518268/167885342-7e2dc604-8bb7-4518-945f-39c8bb7b3ec2.png">

Then it updates correctly once I click inside that small box
<img width="302" alt="Screen Shot 2022-05-11 at 10 15 28 AM" src="https://user-images.githubusercontent.com/10518268/167885594-0fe6a532-f736-4a16-80ea-b0ce2bf5ba13.png">
.

**Comment by yuanqing** [comment]
This should be fixed in `1.9.2`
