### ISSUE TITLE
Disable the plugin's scrollbar

### ISSUE THREAD

**Issue by raf-underscore** [yuanqing/create-figma-plugin#116]
Looking for an option to disable the scrollbar, or if there is already a way, how would one go about doing it?

![image](https://user-images.githubusercontent.com/52125687/180641373-de5f2047-60b0-426d-beab-bdf1691d7fc9.png)

**Comment by yuanqing** [comment]
You can write your own CSS (ie. CSS modules) to achieve this – wrap your root component in a `div` set to `overflow: hidden`

**Comment by raf-underscore** [comment]
Thanks, this solved it!
