### ISSUE TITLE
Dropdown menu is clipped when used in a container with `overflow: auto` or `overflow: hidden`

### ISSUE THREAD

**Issue by yuanqing** [yuanqing/create-figma-plugin#117]
https://github.com/yuanqing/create-figma-plugin/issues/112#issuecomment-1175140905

**Comment by airtable-JayRansijn** [comment]
Is there something similar to https://popper.js.org/ for Preact? Popovers and dropdowns should preferably have an option (or default to) be rendered inside of a portal.
