### ISSUE TITLE
Links contained in centered modals are clickable when the modal is closed

### ISSUE THREAD

**Issue by muryoh** [yuanqing/create-figma-plugin#118]
Because `opacity: 0` does not prevent those links from being clickable: https://github.com/yuanqing/create-figma-plugin/blob/7f31b88c0dbf929d3c49dbaad6e167ef30f17ffa/packages/ui/src/components/modal/modal.css#L19

I think `visibility: hidden/visibile` could be used instead

**Comment by yuanqing** [comment]
I’m not able to reproduce this issue
