### ISSUE TITLE
How to add an image to a plugin?

### ISSUE THREAD

**Issue by jryebread** [yuanqing/create-figma-plugin#120]
trying to add an img to ui.tsx like so: `<img src="mage.png" alt="BigCo Inc. logo"/>`

Result:
![image](https://user-images.githubusercontent.com/22125118/187596916-966db385-6262-4ced-b93a-2a4194cbd847.png)

**Comment by yuanqing** [comment]
https://yuanqing.github.io/create-figma-plugin/recipes/#using-image-assets-in-your-plugin-widget-ui

**Comment by jryebread** [comment]
thanks i missed this one in the docs
