### ISSUE TITLE
once being called twice?

### ISSUE THREAD

**Issue by jryebread** [yuanqing/create-figma-plugin#122]
Hi there, I am having an issue where after calling `emit` in my `main.ts` file, The `on` reciever in `ui.tsx` is being invoked twice or several times.

i am running `emit` after I call an async function to upload an image:

```
        uploadImage(prompt, currentSelection, apiKey).then(packData => {
          console.log("Promise resolved for upload image!");
          emit<Base64Creator>("BASE_64_IMG_CREATE", packData)

        })
        .catch( error => {
          console.log("Error encountered during uploadImage: ", error);
        })
```

```
on('BASE_64_IMG_CREATE', async function (packData: any) {
  console.log("prompt: ", packData)
  setLoading(true);
  const body = {
      prompt: packData.promptStr,
      init_image: packData.base64img,
      seed: Math.floor(Math.random() * 10000000),
      prompt_strength: 0.8,
      num_outputs: 1,
      num_inference_steps: 50,
      width: 512,
      height: 512,
  }
  ...
```

as you can see the "prompt: " console log is being print twice, I know the method where uploadImage is called is only resolved once due to there being one console log of the "promised resolved" line

![image](https://user-images.githubusercontent.com/22125118/189513187-cdc378d8-1a13-4d92-a10f-3bbc96d1c78b.png)

**Comment by jryebread** [comment]
Even if i change it to `on` to `once` for the Base64ImgCreator Handler it still is invoked multiple times, heres one example where it is executed 4 times and i am not sure why
![image](https://user-images.githubusercontent.com/22125118/189554650-73dace47-b388-4d7f-a2b6-b85633e83ee4.png)

**Comment by yuanqing** [comment]
You need to wrap the call to `once` or `on` within a `useEffect` when in a Preact (or React) component
