### ISSUE TITLE
Is there anyway to render image from url?

### ISSUE THREAD

**Issue by Riken-Shah** [yuanqing/create-figma-plugin#123]
Hey, 
Thanks a ton for working on this!

I am building a plugin that shows a lot of images inside a plugin.
If I want to show the image do I have to download it every time and then show it?

**Comment by Riken-Shah** [comment]
Sorry my bad, I was using `<image>`  instead of `<img>`  🤦‍♂️!

**Comment by yuanqing** [comment]
@Riken-Shah See https://yuanqing.github.io/create-figma-plugin/recipes/#using-image-assets-in-your-plugin-widget-ui

**Comment by Riken-Shah** [comment]
Yeah, I initially implemented that flow only, converting the image URL to base64 string and then updating img src. 
But it turns out using `img` with `src` also works!
I should've checked that first before implementing that function.
