### ISSUE TITLE
Setting up environment variables not possible

### ISSUE THREAD

**Issue by niels-bosman** [yuanqing/create-figma-plugin#127]
It would be nice to have a way to easily set up environment variables. This is not really possible at the moment because there is no editable Webpack config. Any ideas / alternatives on how to set this up?

**Comment by yuanqing** [comment]
@niels-bosman – You can use a `build-figma-plugin.main.js` file (or `build-figma-plugin.ui.js` file) to override the underlying esbuild configuration:

```js
module.exports = function (buildOptions) {
  return {
    ...buildOptions,
    define: {
      'process.env.NODE_ENV': `'${process.env.NODE_ENV}'`
    }
  }
}
```

See:
- https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-underlying-esbuild-configuration
- https://esbuild.github.io/api/#define

**Comment by niels-bosman** [comment]
Thanks a lot! I set it up using the `dotenv` package in this way:

```js
const env = JSON.stringify(require("dotenv").config().parsed);

module.exports = buildOptions => ({
  ...buildOptions,
  define: {
    "process.env": env,
  },
});
```

**Comment by LeslieOA** [comment]
> Thanks a lot! I set it up using the `dotenv` package in this way:
> 
> ```js
> const env = JSON.stringify(require("dotenv").config().parsed);
> 
> module.exports = buildOptions => ({
>   ...buildOptions,
>   define: {
>     "process.env": env,
>   },
> });
> ```

If you're creating a plugin in TypeScript, don't forget to install `@types/node`.

**Comment by LeslieOA** [comment]
> Thanks a lot! I set it up using the `dotenv` package in this way:
> 
> ```js
> const env = JSON.stringify(require("dotenv").config().parsed);
> 
> module.exports = buildOptions => ({
>   ...buildOptions,
>   define: {
>     "process.env": env,
>   },
> });
> ```

For future readers/reference: if using TypeScript, don't forget to install `@types/node`.

**Comment by oren-shlomi** [comment]
how would you pass different env? in the script?

**Comment by artivilla** [comment]
I'm not sure where is the right place in the documentation but this would be a really useful recipe to add to the list. On setting env variables.

**Comment by Hosam-hsm** [comment]
I tried your solutions and process.env.VARIABLE is working in the ui.tsx file. But when I try to access process.env.VARIABLE in main.ts file, I am facing the error: 'process' is not defined.
@yuanqing @niels-bosman any help here?
