### ISSUE TITLE
Disclosure click target

### ISSUE THREAD

**Issue by abynim** [yuanqing/create-figma-plugin#128]
I'm trying to use the Disclosure component with a button contained inside it. Currently the click target to toggle the Disclosure covers the entire area of the title and children, so the button inside is not clickable. 

Is this by design, or should the Disclosure's click target be limited to only the title area?

**Comment by abynim** [comment]
I checked an older plugin that was using v1, and it seems this behavior changed at some point. 

Here's the diff: https://github.com/yuanqing/create-figma-plugin/commit/63c01a55f5aedb67147daf12a74d202484b0b5cf#diff-9ce5ac9e0fc8ce8773449882f71c8adb86bd278f628c295310d4280f4c3a2dea

**Comment by yuanqing** [comment]
Can confirm that this is a bug

**Comment by yuanqing** [comment]
@abynim – I just cut a `@create-figma-plugin/ui@2.1.5-alpha.0`. Can you verify if it fixes the issue?

**Comment by abynim** [comment]
Just checked. Works as expected 👍 Thanks for the quick fix, will look out for the official update!

**Comment by yuanqing** [comment]
Fixed in `2.1.5`
