### ISSUE TITLE
Using Tailwind css

### ISSUE THREAD

**Issue by Khaledgarbaya** [yuanqing/create-figma-plugin#133]
Hi,
I would like to use Tailwindcss but seems like things are not working, maybe I am missing something.

Here's my code in the `build-figma-plugins.ui.js`

```js
const postCssPlugin = require("esbuild-style-plugin");

module.exports = function (buildOptions) {
  buildOptions.plugins.push(
    postCssPlugin({
      postcss: {
        plugins: [require("tailwindcss"), require("autoprefixer")],
      },
    })
  );
  return {
    ...buildOptions,
    define: {
      global: "window",
    },
  };
};


```

I appreciate any guidence

**Comment by yuanqing** [comment]
@Khaledgarbaya – One solution may be to use the Tailwind CLI directly:

1. [Invoke the `tailwind` CLI in an `npm` script](https://github.com/alex-streza/summon-ai/blob/078f5c47eaba2c838bd4f9a1a83a3d84bf8bd547/figma/package.json#L26)
2. [Import the generated stylesheet in your UI file](https://github.com/alex-streza/summon-ai/blob/078f5c47eaba2c838bd4f9a1a83a3d84bf8bd547/figma/src/generate-variants/ui.tsx#L23)
    - Note the use of a [`!` prefix before the import path](https://yuanqing.github.io/create-figma-plugin/ui/#using-custom-css) to directly inline the file without hashing the class names

**Comment by Khaledgarbaya** [comment]
@yuanqing Thanks, I think that's the way to do it for now. Great tip about the `!` prefix
