### ISSUE TITLE
Overflowing text in Textbox is clipped at the end

### ISSUE THREAD

**Issue by aashreys** [yuanqing/create-figma-plugin#136]
Notice in the image below `3` at the end is slightly clipped. This happens whenever the text overflows in a single-line Textbox.

<img width="336" alt="CleanShot 2022-12-10 at 17 43 29@2x" src="https://user-images.githubusercontent.com/6137765/206854579-93944834-cd87-457f-8c19-13b800b076c4.png">

Here's the relevant Textbox HTML.

```
<Textbox
{...useInitialFocus()}
placeholder='Paste layer, page or web URL'
value={url}
onValueInput={setUrl}
validateOnBlur={(url) => {
emit(EVENT_URL_UPDATED, { url })
return url
}}
variant="border" />
```

**Comment by yuanqing** [comment]
Fixed in `2.1.6`
