### ISSUE TITLE
Excluding dependencies from ESBuild bundle?

### ISSUE THREAD

**Issue by ben-katz** [yuanqing/create-figma-plugin#144]
I am trying to use [an NPM package](https://github.com/jsscheller/imagemagick-wasm) in my Figma plugin. When I import it, and try and `npm run watch`, I get: 
```
info Building...
error esbuild error
    Build failed with 5 errors:
    node_modules/@jspawn/imagemagick-wasm/magick.js:11:17: ERROR: Could not resolve "path"
    node_modules/@jspawn/imagemagick-wasm/magick.js:11:77: ERROR: Could not resolve "fs"
    node_modules/@jspawn/imagemagick-wasm/magick.js:113:465: ERROR: Could not resolve "child_process"
    node_modules/@jspawn/imagemagick-wasm/magick.mjs:12:35: ERROR: Could not resolve "path"
    node_modules/@jspawn/imagemagick-wasm/magick.mjs:12:51: ERROR: Could not resolve "module"  
```
I tried [asking the developer](https://github.com/jsscheller/imagemagick-wasm/issues/1) of the package, but I still can't figure out how to get it to work. I know that libraries like `fs` and `path` shouldn't work on the browser, but according to the developer: 

> They never actually get imported In the browser environment but it looks like ESBuild is statically analyzing the imports and notices those are missing

Okay, so let's exclude them then? I did some googling and found out about the [--external](https://github.com/evanw/esbuild/issues/40), flag, however when I add that to `package.json` of my plugin like so:

```
...
  "scripts": {
    "build": "build-figma-plugin --typecheck --minify --external:fs",
    "watch": "build-figma-plugin --typecheck --watch --external:fs"
  } ...
```

... I still get the same error:
```
info Building...
error esbuild error
    Build failed with 5 errors:
    node_modules/@jspawn/imagemagick-wasm/magick.js:11:17: ERROR: Could not resolve "path"
    node_modules/@jspawn/imagemagick-wasm/magick.js:11:77: ERROR: Could not resolve "fs"
    node_modules/@jspawn/imagemagick-wasm/magick.js:113:465: ERROR: Could not resolve "child_process"
    node_modules/@jspawn/imagemagick-wasm/magick.mjs:12:35: ERROR: Could not resolve "path"
    node_modules/@jspawn/imagemagick-wasm/magick.mjs:12:51: ERROR: Could not resolve "module"  
```
It doesn't seem like `fs` is actually being excluded - or maybe I am misinterpreting this build output. 

I am very new to the world of build tooling etc, so I would greatly appreciate some help understanding all of this. Thank you.

**Comment by yuanqing** [comment]
@ben-katz – The `build-figma-plugin` CLI does not have an `external` option. See [this recipe from the docs](https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-underlying-esbuild-configuration). I think creating a `build-figma-plugin.main.js` containing the following should work:

```js
module.exports = function (buildOptions) {
  return {
    ...buildOptions,
    external: ['fs']
  }
}
```

(If you’re looking to modify the esbuild configuration for the UI bundle, use a file named `build-figma-plugin.ui.js`)

**Comment by ben-katz** [comment]
> If you’re looking to modify the esbuild configuration for the UI bundle, use a file named `build-figma-plugin.ui.js`

Thanks so much, this worked. However I am having some other issues now but I think they might be related to the npm package I am trying to use. If it's okay with you, I'll leave this issue open until I'm certain it's working.

**Comment by Yaroslavpnts** [comment]
But how we can achieve next case.
If we want to exclude some dependency form bundle, but still want ho have it in node_modules after compling?
So we need all dependencies from node_modules be in bundle and in node_modules we should have only 1 dependency, that was excluded from bundle?
