### ISSUE TITLE
Possible to use npm packages within plugin? 

### ISSUE THREAD

**Issue by therealtimhawkins** [yuanqing/create-figma-plugin#145]
Hi there,

I am trying to use an [npm package](https://www.npmjs.com/package/axios) from within my plugin but I am getting the error:
```
TypeError: cannot read property 'FormData' of undefined
 at node_modules/form-data/lib/browser.js (PLUGIN_83_SOURCE:556)
```

Is it possible to install and use packages within the plugin or am I missing something?

Thanks!

**Comment by yuanqing** [comment]
`axios` should work if you try to import it in the UI context. See https://www.figma.com/plugin-docs/how-plugins-run

**Comment by therealtimhawkins** [comment]
Thanks a lot! Works perfectly, I should have read the docs more carefully...
