### ISSUE TITLE
Sending built-in Figma events like "drop"

### ISSUE THREAD

**Issue by ben-katz** [yuanqing/create-figma-plugin#146]
How would I go about using the events described here: https://www.figma.com/plugin-docs/api/properties/figma-on

I am not sure how to use them with the types.ts handlers etc.

**Comment by ben-katz** [comment]
For context, I am trying to do a drag and drop icon library and need access to Figma's "absoluteX" and "abosluteY" values, but these seem to be only given as part of the built in "drop" event.

**Comment by yuanqing** [comment]
Hope you’ve managed to figure this out! I can share a reference from my `Insert Big Image` plugin: https://github.com/yuanqing/figma-plugins/blob/7152b224b764775c300334e94e2e8df83695d7d8/packages/figma-insert-big-image/src/main.ts#L30-L53
