### ISSUE TITLE
Enable build for browser

### ISSUE THREAD

**Issue by stepan662** [yuanqing/create-figma-plugin#147]
I found out that you can quite simply run the plugin UI in iframe and "simulate" figma by sending messages. I found this useful for creating cypress tests however, when I want to use your build setup it's not so straight forward and I needed to go with a quite hacky solution and creating an alternative package.json with alternative configuration.
https://github.com/tolgee/figma-plugin-tolgee/pull/1

Would it be possible to add this setup to this repo, so it's easier to test?

**Comment by yuanqing** [comment]
It’s unlikely that I’ll need this so I’d say that this is beyond the scope of this toolkit for now
