### ISSUE TITLE
Properties of an object are lost between emit and the on event handler.

### ISSUE THREAD

**Issue by danhendersonede** [yuanqing/create-figma-plugin#154]
I'm trying to emit a FrameNode from main to ui, but for some reason, all but `id` is stripped from the object.

Before emit: All expected properties are available.
<img width="405" alt="image" src="https://user-images.githubusercontent.com/82847291/228750198-84adf122-fcc7-4249-8252-78a9b07cc757.png">

On event: Only the ID is available
<img width="256" alt="image" src="https://user-images.githubusercontent.com/82847291/228751454-0985e563-7d43-4e31-aeed-7015cc6ef270.png">

Here's my EventHandler, expecting a whole FrameNode
`export interface SelectionChangeHandler extends EventHandler {
  name: "SELECTION_CHANGE",
  handler: (node: FrameNode) => void
}`

**Comment by yuanqing** [comment]
Only plain objects can be passed via `emit`. What I do is to use the `extractAttributes` utility to pick the values I need into a plain object and then pass that plain object to `emit`

**Comment by danhendersonede** [comment]
Thank you!
