### ISSUE TITLE
manifest.json is generated in the root folder but not "build" folder

### ISSUE THREAD

**Issue by angusjune** [yuanqing/create-figma-plugin#157]

**Comment by yuanqing** [comment]
Setting the output directory for the `manifest.json` and JavaScript bundles will be possible in `2.6.0` via a new `--output` CLI flag

**Comment by fwextensions** [comment]
@yuanqing how is the flag supposed to be specified?  Like `--output=dist`?  `--output dist`?   `--output=./dist`?  I tried various combinations on Windows 11 and didn't see any effect.  The manifest is still output to the root directory, and the JS files to `/build`.
