### ISSUE TITLE
Cant run storybook in plugin built using create-figma-plugin-ui

### ISSUE THREAD

**Issue by mgWaring** [yuanqing/create-figma-plugin#158]
I'm struggling to get storybook to build in our plugin repo. I seems to be having issues with the css in the create-figma-plugin-ui repo. The plugin itself builds and runs fine.

I've tried extending the webpack config with custom loaders targeted at css, sass and scss - with no luck.
I've tried reconfiguring storybook to use `@storybook/builder-vite` and that throws it's own host of distinctly unhelpful errors.

Below is the error I get when using the weback5 framework, which innocently reads like I just need to add a css loader to the webpack config, but doing so doesn't change a thing (also makes me feel weird that we might need to process something coming from the `node_modules` folder...):

```
ERROR in ./node_modules/@create-figma-plugin/ui/lib/css/base.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url('https://fonts.googleapis.com/css?family=Inter:400,600&display=swap');`
```

I feel like I'm probably very close, and (as with most things js build related) I'm just one config option off getting this to build properly. Our code at the moment is very basic - just a few preact components and vanilla (unprocessed) css - so I can only think that I need to add something to the default `.storybook/main.js` file to tell it how to handle the create-figma-plugin-ui code?

i.e. this:

```
import type { StorybookConfig } from '@storybook/preact-webpack5';

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/preact-webpack5', //keeping things as vanilla as possible to rule out cross contamination
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
};
export default config;
```

Any help would be much appreciated!

**Comment by yuanqing** [comment]
My only suggestion would be to refer to the `.storybook` folder in the repo and try to use the same dependencies (with the same versions) for your setup
