### ISSUE TITLE
Suggestion: make the library of components compatible with React projects?

### ISSUE THREAD

**Issue by alexstrat** [yuanqing/create-figma-plugin#159]
As of today and after a quick research, `@create-figma-plugin/ui` is the most accomplished (quality and quantity) and maintained of the publicly available libraries of components that replicates the Figma/FigJam UI. _See a list of alternatives below._

_That's awesome and thank you for your work 🎉_

Though, this library is not accessible to React projects (#88) because it's in Preact and using Preact components in React is not possible (or [very cumbersome](https://swizec.com/blog/seamlessly-render-a-preact-component-in-a-react-project/)) — while using React components in Preact [is supported](https://preactjs.com/guide/v10/switching-to-preact/).

For many, using Preact instead of React is not an option.

Hence my brutal suggestion to trigger a discussion:
> move the library of components from Preact to React

because 1/ the amount of work to migrate is _apriori_ reasonable (since it's "just" JSX) and that 2/ the support for Preact will stay unchanged (or minor impact).

What are the thoughts about it?

---
I'd understand that it is very probably out of the scope of the project and that this suggestion will receive a negative response, but I thought that we were lacking a place where the subject was brought up, discussed and maybe answered, and where we could share solutions and alternatives.

https://github.com/jhardy/figma-styled-components/
https://github.com/JB1905/react-figma-ui
https://github.com/LiamMartens/figma-react-ui-kit/
https://github.com/alexandrtovmach/react-figma-plugin-ds

**Comment by yuanqing** [comment]
Without funding, it’s unlikely that I’ll be able to invest time to migrate to React or support a feature that I don’t personally find useful to my own plugin work

Hopefully, [this recipe provided in the docs](https://yuanqing.github.io/create-figma-plugin/ui/#using-react) for using React alongside the Preact components works for you. And, another alternative to add to the libraries you listed would be [this React fork of the UI library](https://github.com/greeeg/figma-ui-kit)
