### ISSUE TITLE
Update RangeSlider to match (new) figma native UI

### ISSUE THREAD

**Issue by romaincointepas** [yuanqing/create-figma-plugin#163]
Not sure when that change was made in Figma, but the slider looks different than the `RangeSlider` component from this library.

<img width="410" alt="Screenshot 2023-05-07 at 7 24 08 PM" src="https://user-images.githubusercontent.com/797899/236692924-72a267d9-cede-4489-be24-e347a50cc97c.png">

**Comment by yuanqing** [comment]
Closing – the plan is to update all components to align with the UI3 visual design
