### ISSUE TITLE
Support for `networkAccess` in manifest file

### ISSUE THREAD

**Issue by sohei1l** [yuanqing/create-figma-plugin#164]
Figma introduced a new property to allowlist the plugin api calls and added an optional networkAccess key to the plugin manifest: https://www.figma.com/plugin-docs/updates/2023/05/10/version-1-update-66/

The Create figma plugin doesn't recognize and parse this property from package.json to add its value to manifest file.

<img width="504" alt="image" src="https://github.com/yuanqing/create-figma-plugin/assets/17885979/b5caac46-f4b4-40b0-8db0-85c762861491">

**Comment by yuanqing** [comment]
@sohei1l – Thanks for flagging this! What you could do in the interim is to [override the generated `manifest.json` using a `build-figma-plugin.manifest.js` file](https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-manifest-json-file):

```js
// build-figma-plugin.manifest.js

module.exports = function (manifest) {
  // ...
  return {
    ...manifest,
    networkAccess: {
      allowedDomains: [
        // ...
      ]
    }
  }
}
```

**Comment by yuanqing** [comment]
Native support for `networkAccess` (without having to use a `build-figma-plugin.manifest.js`) will ship in `2.6.0`
