### ISSUE TITLE
Could not resolve external dependency

### ISSUE THREAD

**Issue by kamleshchandnani** [yuanqing/create-figma-plugin#166]
I tried adding '@sentry/analytics-next' and when I run watch/build command it throws error
```
error esbuild error
    Build failed with 1 error:
    src/main.ts:8:24: ERROR: Could not resolve "'@sentry/analytics-next"
```

I tried adding another dependency i.e `@sentry/browser` assuming that there might be issue with this library but that also throws the same error

```
error esbuild error
    Build failed with 1 error:
    src/main.ts:8:24: ERROR: Could not resolve "@sentry/browser"
```

ofcourse the dependencies are installed in the `node_modules` directory

Template: React Editor
Node: v18.12.1
`@create-figma-plugin/utilities` Version: 2.5.0

**Comment by kamleshchandnani** [comment]
@yuanqing 👆

**Comment by kamleshchandnani** [comment]
figured out the problem, the issue was happening where for `main.tsx` the config has value of `platform` set to `neutral`. Reading from esbuild docs
<img width="1053" alt="Screenshot 2023-07-12 at 2 25 53 PM" src="https://github.com/yuanqing/create-figma-plugin/assets/11384858/b0fe20e0-f0d1-4836-8b47-2dc4f276f795">

they reset the main and module fields to be empty when `platform: neutral`. Not sure what is the exact reason of setting this to `neutral` in the esbuild's config.

**Comment by salamaashoush** [comment]
@kamleshchandnani Yes that was the problem for me also, I worked around it by adding `build-figma-plugin.main.js` file and overriding the `mainFields` config

```
/**
 *
 * @param {import('esbuild').BuildOptions} buildOptions
 * @returns  {import('esbuild').BuildOptions}
 */
module.exports = function (buildOptions) {
  return {
    ...buildOptions,
    mainFields: ['module', 'main', 'browser'],
  };
};
```
