### ISSUE TITLE
how to add yaml loader

### ISSUE THREAD

**Issue by sherlockfeng** [yuanqing/create-figma-plugin#168]
for now, i use yaml file in my plugin, but here is the error
<img width="640" alt="image" src="https://github.com/yuanqing/create-figma-plugin/assets/11866967/03fa5e35-17ef-499c-afe5-bfcc785291a8">

**Comment by yuanqing** [comment]
See https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-underlying-esbuild-configuration
