### ISSUE TITLE
UI recipe example for using react

### ISSUE THREAD

**Issue by softmarshmallow** [yuanqing/create-figma-plugin#18]
react example of how to render react project on cfp

**Comment by Jeremy-Knudsen** [comment]
would like to see an exmaple of how to integrate a React component using preact-compat

**Comment by softmarshmallow** [comment]
here's my project and it might help you. https://github.com/bridgedxyz/assistant

**Comment by yuanqing** [comment]
Create Figma Plugin is currently set up to [work out-of-the-box with Preact](https://yuanqing.github.io/create-figma-plugin/#adding-a-ui-to-a-plugin-command), not React.

---

See [this repo](https://github.com/yuanqing/create-figma-plugin-react-example) for an example of how to use React with Create Figma Plugin. There are two key things that must be configured:

1. You need to use a [`figma-plugin.config.js`](https://github.com/yuanqing/create-figma-plugin-react-example/blob/3ecf55085fc672bd7ebcbe04b4bab0c2a9b62ef1/figma-plugin.config.js) file to override the underlying Webpack configuration.

2. You need to set `"jsxFactory"` to `"React.createElement"` in the [`tsconfig.json`](https://github.com/yuanqing/create-figma-plugin-react-example/blob/3ecf55085fc672bd7ebcbe04b4bab0c2a9b62ef1/tsconfig.json#L4).

Note that by doing the above, you will no longer be able to leverage the `@create-figma-plugin/ui` component library.

**Comment by yuanqing** [comment]
@Jeremy-Knudsen The [`figma-plugin.config.js` file is an escape hatch](https://yuanqing.github.io/create-figma-plugin/#customizing-the-underlying-webpack-configuration), and you can use it to customize the Webpack build step, including setting up [`preact-compat`](https://preactjs.com/guide/v8/switching-to-preact/#aliasing-via-webpack)

**Comment by fnky** [comment]
It's fairly straightforward to add some React compatibility for preact, albeit with some pitfalls:

Add the following to your `tsconfig.json`:

```json
"compilerOptions": {
  "paths": {
    "react": ["node_modules/preact/compat"],
    "react-dom": ["node_modules/preact/compat"]
  },
  "baseUrl": "."
}
```

Add the following to the `figma-plugin.config.js` file:

```js
module.exports = (webpackConfig) => ({
  ...webpackConfig,
  resolve: {
    ...webpackConfig.resolve,
    alias: {
      ...webpackConfig.resolve.alias,
      react: "preact/compat",
      "react-dom": "preact/compat",
    },
  },
  stats: "detailed",
});
```

This will more or less set you up to support some React-specific libraries.

However, you may have to fix typings for some things like `RefObject` and `EventHandler` types. This can be achieved by creating a definitions file, for example `react.d.ts` in the src folder. You'll then just extend the module declaration for react (without the need for `@types/react`)

```
declare module "react" {
  // Add React types here. Some can be aliased from preact and preact/compat like so:
  export {
    PreactContext as Context,
    PreactProvider as Provider,
    VNode as ReactElement,
    VNode as ReactNode,
    Ref,
    JSX,
    RefObject,
    RenderableProps as ComponentPropsWithRef,
    // and more if you need it...
  } from "preact";
}
```

It does add some friction if you rely on a lot of React components with heavy use of React types; e.g. event handlers etc. But you can loosen your tsconfig, too if that becomes a problem.

**Comment by Jeremy-Knudsen** [comment]
I appreciate all the responses! Thanks **fnky** and **yuanqing**!

**Comment by yuanqing** [comment]
Closing this for now as the suggested solution is no longer relevant given the move to esbuild as of `v1`
