### ISSUE TITLE
Swap ESBuild for Bun

### ISSUE THREAD

**Issue by ben-katz** [yuanqing/create-figma-plugin#190]
Not sure the best way to title this, but it would be cool to see support for Bun. If I have anything to contribute from testing I will add it here.

**Comment by yuanqing** [comment]
Would love to see how Bun could be helpful; do share the results of your tests!

That said, I do see Node.js still being the primary supported runtime given that it’s still more mainstream and stable than Bun at the moment. The current bundler powered by `esbuild` is also super quick already as-is; `--watch` mode is effectively instant for me

**Comment by TheUltDev** [comment]
Not possible as Bun doesn't support older targets.
You need to target 2017 for the plugin code.
Already went down this rabbit hole, don't waste your time yet.
