### ISSUE TITLE
Pressing enter in a TextBox shouldn't blur it

### ISSUE THREAD

**Issue by fwextensions** [yuanqing/create-figma-plugin#192]
I see this code in the `raw-textbox.tsx`:

```
      if (key === 'Enter') {
        event.currentTarget.blur()
        return
      }
```

I'm not sure why an input field should ever blur itself, as opposed to letting some other code change the focus.  If you really want to blur it on enter, you could do it in `onKeyDown`.  But there's currently no way to override this built-in behavior.

**Comment by yuanqing** [comment]
Agreed. I’m working on some larger (potentially breaking) changes across the UI library, including a way to make this configurable

**Comment by fwextensions** [comment]
Looks like this happens in dropdowns as well, presumably because keyboard focus is tied to the menu visibility, which I noted in #193.

**Comment by fwextensions** [comment]
This is working great in v3!
