### ISSUE TITLE
Npm watch not updated interface plugin in figma

### ISSUE THREAD

**Issue by lucasmiqueias** [yuanqing/create-figma-plugin#215]
Hi guys.

I've been using this pattern for some time to study and develop a plugin, but "npm watch" never updated the plugin interface.
Does anyone else go through this?

I create issue on Figma communit to.
https://forum.figma.com/t/hot-reload-not-working-with-react/46831

**Comment by yuanqing** [comment]
Create Figma Plugin does not support hot reload
