### ISSUE TITLE
esbuild error: could not resolve "@create-figma-plugin/utilities"

### ISSUE THREAD

**Issue by parkersweb** [yuanqing/create-figma-plugin#216]
Hi there,

My plugin recently started failing on both watch and build with the following error:

```
info Building...
error esbuild error
    Build failed with 1 error:
    src/main.ts:1:29: ERROR: Could not resolve "@create-figma-plugin/utilities"
```

In trying to chase down the cause of the problem - I've run `npx --yes create-figma-plugin` to create entirely fresh plugins using both the `preact-rectangles` and the `preact-tailwindcss` templates and both of those fail with the same error.

I'm using node Node v20.9

Does anyone have any suggestions as to what might be the cause? Thanks so much!

**Comment by yuanqing** [comment]
I can’t seem to reproduce this issue on my machine (node v20 on a Mac). Have you tried bootstrapping using `npx --yes create-figma-plugin@latest`

**Comment by parkersweb** [comment]
Yeah - still gives the same error 😬  

I installed node 20 through nvm - on Sonoma 14.2. Does that match your setup? Slightly stumped at the moment!

**Comment by yuanqing** [comment]
So strange

> I installed node 20 through nvm - on Sonoma 14.2

Same except that I’m on 14.1. I doubt it’s something to do with the OS
