### ISSUE TITLE
Do you have any plans to apply for codegen

### ISSUE THREAD

**Issue by mineclover** [yuanqing/create-figma-plugin#218]
package.json's figam-plugin property is outputting that the codegenLanguages property is not available

Because it creates a manifest based on the attribute of package.json, if you use create-figma-plugin, you can't make codegen plugins..

I wonder if there are any plans to support codegen in the future

**Comment by yuanqing** [comment]
Yes, there are plans to support configuring all codegen-related properties via the `package.json`. In the meantime, what you can do is use a `build-figma-plugin.manifest.js` file to customize the `manifest.json` file that’s output. See https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-manifest-json-file

**Comment by mineclover** [comment]
thank you, I was looking for this
can close the issue
