### ISSUE TITLE
get the list of elements in canonical order

### ISSUE THREAD

**Issue by leo-martin** [yuanqing/create-figma-plugin#219]
Hello,

I'm developing a plugin to export content from a figma design and I'm using the traverseNode function. One problem I have with it is the depth first, is it possible to get the list of elements in order ?

for example if my figma file looks like this :

```
body
  div
   span
   img
```
I would like to get this list `[body, div, span, img]` but I'm getting `[body, div, img, span]`

Is there any function that can help me achieve that?

Thank you

**Comment by davo** [comment]
Hey @leo-martin,
Have you checked the function `sortNodesByCanonicalOrder` on [`/utilities`](https://github.com/yuanqing/create-figma-plugin/blob/main/packages/utilities/src/node/sort-nodes/sort-nodes-by-canonical-order.ts)?
