### ISSUE TITLE
buildManifestAsync does not create valid menu entry

### ISSUE THREAD

**Issue by karmacod3r** [yuanqing/create-figma-plugin#221]
When I configure the menu entry according to this reference: https://www.figma.com/plugin-docs/manifest/ the watch and build scripts do only copy the menu names to the manifest. 
Why does the create-figma-plugin config have a different structure for menus? https://yuanqing.github.io/create-figma-plugin/configuration/

**Comment by yuanqing** [comment]
The different configuration API is to allow you to write each menu command as separate files, which helps with maintainability. If you prefer to do this wiring manually and write a `manifest.json` by hand, then I don’t think you actually need to reach for this framework

**Comment by Schoenhofer-Humain** [comment]
Yes, I got confused and didn't realise the difference to manifest.json. Works perfectly now, thanks.

**Comment by karmacod3r** [comment]
Yes, I got confused and didn't realise the difference to manifest.json. Works perfectly now, thanks.
