### ISSUE TITLE
`networkAccess` stripped from manifest.json

### ISSUE THREAD

**Issue by frisfruitig** [yuanqing/create-figma-plugin#223]
According to issue #164, `networkAccess` is supported in manifest.json. However, when I add it, it is always stripped when running watch or build scripts.
The only way for me to add this property, is to use the suggested workaround from #164 and using a separate file to [customize the manifest.json](https://yuanqing.github.io/create-figma-plugin/recipes/#customizing-the-manifest-json-file).

Is this intended?

**Comment by yuanqing** [comment]
@frisfruitig – This shouldn’t be happening with the latest version (`3.2.0`) – can you verify?

**Comment by frisfruitig** [comment]
Hey @yuanqing. With `3.2.0` I still get the same behavior.

Steps I took to try to verify:

1. Create a new plugin from Figma (I selected a 'Figma only' plugin, with a custom UI)
2. Install `@create-figma-plugin/build` and `@create-figma-plugin/tsconfig` as devDependencies
3. Replace the build and watch scripts with `"build-figma-plugin --typecheck --minify"` and `"build-figma-plugin --typecheck --watch"` respectively.
4. Define `networkAccess` in the manifest.json. This step is optional, because the generated plugin from Figma will now come with a predefined value.
5. Build.

Maybe I'm overlooking something. If so, let me know what I can do differently. Otherwise, I hope this helps!

**Comment by yuanqing** [comment]
The `”networkAccess”` key (like all other configuration used by the Create Figma Plugin framework) needs to be defined in `package.json`, under the `”figma-plugin”` key

**Comment by frisfruitig** [comment]
Ok, then I definitely overlooked something. Can confirm this works.
Sorry for the confusion, and thanks for the help!

**Comment by yuanqing** [comment]
No worries! Definitely something that can be improved in the docs as well
