### ISSUE TITLE
esbuild plug-ins postcss / tailwindcss not working

### ISSUE THREAD

**Issue by emkayy** [yuanqing/create-figma-plugin#229]
I tried adding tailwind through an esbuild plug-in in various different ways. However, it seems like the plug-ins are never initiated.
This is my build-figma-plugin.main.js:
```
const { tailwindPlugin } = require("esbuild-plugin-tailwindcss");
const postcss = require("esbuild-postcss");

module.exports = function (buildOptions) {
  const config = {
    ...buildOptions,
    plugins: [...buildOptions.plugins, postcss() /* tailwindPlugin() */],
  };
  return config;
};
```

I also tried passing the plugin config directly:
```
plugins: [
    postcss({
      plugins: [
        tailwindcss('./tailwind.config.js'), // also tried without config path and passing config object
      ],
    }),
  ],
```
Here is a minimal setup
[tailwindpostcss.zip](https://github.com/yuanqing/create-figma-plugin/files/15051913/tailwindpostcss.zip)

Is there a special way you have to add / configure esbuild plug-ins?

**Comment by yuanqing** [comment]
Suggest using the `plugin/preact-tailwindcss` template
