### ISSUE TITLE
missing support for fragements

### ISSUE THREAD

**Issue by artivilla** [yuanqing/create-figma-plugin#232]
This should work out of the box since preact supports fragments. Using `<div>` for now but would love support for this.

![image](https://github.com/yuanqing/create-figma-plugin/assets/2120159/c461cb73-12c5-406f-be31-2ccb9a45039c)

**Comment by yuanqing** [comment]
This should work:

```tsx
import { Fragment } from 'preact'

// ...

<Fragment></Fragment>
```
