### ISSUE TITLE
feature request: accept a map of ui in manifest

### ISSUE THREAD

**Issue by artivilla** [yuanqing/create-figma-plugin#248]
Description: 
Currently the plugin only creates a single UI file but if we want multiple headers to the plugin, they need to generate separate Uis during build.

The plugin manifest accepts `ui?: string | { [key: string]: string }` . Would you be open accepting a PR? I see 6 PRs already open so not sure if you need help.

**Comment by yuanqing** [comment]
No current plans to add this behavior. Having different UI for different commands is already supported today, and the ability to output the UI into separate files seems unnecessary
