### ISSUE TITLE
Possible lint error

### ISSUE THREAD

**Issue by jamesgrubb** [yuanqing/create-figma-plugin#251]
I have an possible lint error (does not effect build):  block-size: 280, ⇔ height: 280, 💪Logical Properties(physical-property-detected). It appears on
```
export default function () {
  showUI({
    height: 280,      
    width: 240
  });
  ```
  Basically wherever I use the words width and height. Any ideas how to fix this? Thanks.

**Comment by yuanqing** [comment]
I think you might need to turn off your lint rules causing the error. Unfortunately it’s not reasonable to change the API to remove all instances of width/height in order to prevent lint errors
