### ISSUE TITLE
Build logs showing errors as [object Object]

### ISSUE THREAD

**Issue by k2589** [yuanqing/create-figma-plugin#26]
On Mac OS 10.15.7, ZSH, TypeScript v 4.2.3 I'm getting not descriptive errors:
<img width="180" alt="Снимок экрана 2021-03-27 в 10 47 49" src="https://user-images.githubusercontent.com/6420066/112714205-4bcab780-8eea-11eb-8ee6-091bab8cba43.png">

Is it expected behavior or maybe I need to set up something from my side?

**Comment by yuanqing** [comment]
Hey! I’ve just published a new version `0.0.84` to npm that includes #24, which is the fix for this issue
