### ISSUE TITLE
Build question/issues

### ISSUE THREAD

**Issue by reintroducing** [yuanqing/create-figma-plugin#32]
Hello,
I was looking at the documentation and trying to figure out the best way to build the plugin (I'm using version `0.0.84` by the way). Here are my questions:

1. Does the `build` command minification really matter? I know typically in web projects we want to minify the output, but it doesn't seem entirely necessary here. The reason I ask is because...
2. A new build overwrites the `manifest.json` file in the root of the repo. Because the manifest isn't output in the build directory (https://github.com/yuanqing/create-figma-plugin/issues/21), it gets overwritten and you have to then re-add a new generated ID from Figma for the plugin (because by default it sets the `id` field to something arbitrary that doesn't match the old `id` that Figma needs). This means that the plugin is actually registered as a completely new plugin on the Figma plugins page.
3. I'm assuming that we are supposed to bump the API version field ourselves as well? This is not something Figma or the plugin do for you? I know that it would be hard for the plugin to figure out what version it should be, but I just want to make sure I understand this correctly as to what the proper process for building should be.

**Comment by reintroducing** [comment]
I just realized that even running the plugin in watch mode during dev ALSO resets the manifest file. This makes it incredibly difficult to retain the plugin ID and version for a future publish of a new version of the plugin because they're always reset to the ID that was used to set up the plugin (at which point you don't have the publishable ID for the plugin) and the first API version (which was `1.0.0`). I feel like I'm missing something here but I can't figure out why these resets keep happening.

**Comment by reintroducing** [comment]
welp, once again, i did not understand the documentation, lol. i started to read your source and realized i can set the `apiVersion` and `id` parameters in package.json and thats what is used to build the manifest dynamically. Disregard all this noise :)

**Comment by yuanqing** [comment]
Glad to see you figured it out!

1. The `--minify` flag for the `build-figma-plugin` CLI is new – it is not in `v0.0.84`.
2. I republished the old `v0.0.84` docs to avoid confusion. https://yuanqing.github.io/create-figma-plugin/

**Comment by reintroducing** [comment]
yeah, i actually completely misunderstood `apiVersion`, as that's just the Figma version of their API and nothing to do with versioning your Figma plugin (which actually doesn't exist at all, its just called `Version 1`, `Version 2`, etc every time you re-publish it). As for the ID, i had completely forgotten I set it when I first created the project a few weeks ago, lol. I was wondering where the heck my id value was coming from and then i remembered its in the `figma-plugin` key in `package.json` and that the docs had said i'll need a real one when I do publish :)
