### ISSUE TITLE
Upgrade to 1.0.1 Fails

### ISSUE THREAD

**Issue by reintroducing** [yuanqing/create-figma-plugin#35]
Hello,
Just tried upgrading to the latest version and when I try to run start I immediately get the following:
```
/Users/mprzybylski/Work/fe-pulse/node_modules/@create-figma-plugin/build/lib/cli.js:2
import sade from 'sade';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

node 12.13.0
npm 6.12.0

**Comment by yuanqing** [comment]
The reason is likely that you need to upgrade your Node.js. My local and the CI both uses v14. At a minimum I think v12.20 should work too

**Comment by reintroducing** [comment]
I figured as much but we’re not ready to upgrade the node version yet in that repo, unfortunately. It would probably be a good idea to add the engines object to the package.JSON outlining the lowest node version that you need as well.

**Comment by Jeremy-Knudsen** [comment]
I upgraded too and it broke things. I don't know how to resolve the errors I am seeing, so I'm going to try to rewrite from scratch.

**Comment by yuanqing** [comment]
https://github.com/yuanqing/create-figma-plugin/blob/main/CHANGELOG.md#100 could be a helpful reference for migrating

**Comment by reintroducing** [comment]
I followed the change log when making my code updates but unless I missed it, I did not see any notes about a necessary node version.

**Comment by yuanqing** [comment]
Yeah, it’s on the website but not in the Changelog. Something definitely worth calling out for sure.

**Comment by yuanqing** [comment]
A note about the version requirements for `v1` has been added to the Changelog
