### ISSUE TITLE
Unable to build/watch 

### ISSUE THREAD

**Issue by artemartemov** [yuanqing/create-figma-plugin#39]
Hello, 

Thanks for putting this together. Super helpful start to getting plugin up and running.

I noticed this morning I am running into issues of building out a fresh plugin. Having tried both the steps you have outlined within the quick start, as well as ommiting the `--yes` flag I am unable to get past the build step.

If I ommit the `--yes` flag, after filling in all the fields, I am returned with this error:
```
error The "path" argument must be of type string. Received undefined
```

If I follow the direction in quick start, after running `npm run watch` or `npm run build` I am presented with the same error of:
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '/Users/aartemov/dev/figma-hello-world/node_modules/postcss-modules/' imported from /Users/aartemov/dev/figma-hello-world/node_modules/@create-figma-plugin/build/lib/utilities/build-bundles-async/esbuild-css-modules-plugin.js
    at legacyMainResolve (internal/modules/esm/resolve.js:225:9)
    at packageResolve (internal/modules/esm/resolve.js:648:14)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I tried using different node versions, both 12.20... and 12.14... 

I have also tried clearing out the package-lock and the node_modules and reinstalling with yarn and then running using yarn but no luck there either. 

Thanks in advance!

**Comment by yuanqing** [comment]
@artemartemov Thanks for reporting this

- Node `v14` is **required** if you want to use v1 of all the Create Figma Plugin packages
- If you’re migrating from an earlier version (eg. `0.0.84` or earlier), see the [Changelog](https://github.com/yuanqing/create-figma-plugin/blob/main/CHANGELOG.md#100)
