### ISSUE TITLE
Menu handler doc

### ISSUE THREAD

**Issue by weilinzung** [yuanqing/create-figma-plugin#44]
Hi, I see your example that we can you can specify a  handler for it. I want to know if version `"0.0.84"` supports it?

I basically want to use the same code but be able to pass in condition, can I use this for? 

Thanks!

```
        "menu": [
          {
            "name": "Select Components",
            "main": {
              "src": "src/select-nodes-by-attribute/main.ts",
              "handler": "selectComponents"
            }
          },
```

**Comment by yuanqing** [comment]
The configuration you shared *should* work with `0.0.84`. You can refer to the docs for that version https://github.com/yuanqing/create-figma-plugin/blob/v0.0.84/docs/configuration.md#menu

**Comment by weilinzung** [comment]
Can you explain a bit more how to be able to check what handler passes in from the main.ts file?

Also, I don't see handler(s) are added to manifest.json?

**Comment by weilinzung** [comment]
Just figured out 

main.tsx:

```
export const CURRENT_PAGE = () => {
  ...shared code...
};
```
