### ISSUE TITLE
tsx error at importing css style.

### ISSUE THREAD

**Issue by casamia918** [yuanqing/create-figma-plugin#46]
<img width="1673" alt="스크린샷 2021-07-21 오후 9 20 57" src="https://user-images.githubusercontent.com/8295005/126487555-39defa94-be9d-44dc-95ae-8a2fb30008d0.png">

### Step to reproduce

Just create new create-figma-plugin project., with npx command.
`npx create-figma-plugin figma-hello-world `
Select "ui" template.
Create new style.css file. Import it from ui.tsx. 

### Version
```json
// Package.json
  "dependencies": {
    "@create-figma-plugin/ui": "^1.2.2",
    "@create-figma-plugin/utilities": "^1.2.2",
    "preact": "^10"
  },
  "devDependencies": {
    "@create-figma-plugin/build": "^1.2.2",
    "@create-figma-plugin/tsconfig": "^1.2.2",
    "@figma/plugin-typings": "^1",
    "typescript": "^4"
  },

```

**Comment by yuanqing** [comment]
You need to run `npm run build` once to generate the typings for the `style.css` file

**Comment by casamia918** [comment]
Thanks. Now I See. 

I should run build or watch to create type declaration file (style.css.d.ts). 

It would be better to be mentioned in document page : [Using custom CSS](https://yuanqing.github.io/create-figma-plugin/#using-custom-css)
