### ISSUE TITLE
Custom styling issue

### ISSUE THREAD

**Issue by casamia918** [yuanqing/create-figma-plugin#48]
I want to change font-size of text component. 

At now, create-figma-plugin support few text props.

<img width="1561" alt="스크린샷 2021-07-22 오전 8 38 04" src="https://user-images.githubusercontent.com/8295005/126572922-afdee497-cac2-498a-8eaf-88d413346a32.png">

So, I tried to use base css style of [figma-plugin-ds](https://github.com/thomas-lowry/figma-plugin-ds), not this one.

I've imported figma-plugin-ds style at the top of ui.tsx file. And set div element's class name from the figma-plugin-ds.
`import "figma-plugin-ds/dist/figma-plugin-ds"`

But nothing happens. Only the base css of @create-figma-plugin/ui is applied.

So, what is the best way to customize css styling?

**Comment by yuanqing** [comment]
The `.css` file extension is required when importing a CSS file.

Just shipped a fix for importing CSS files from `node_modules`. The following code should work as of version `1.2.3`:

```
import 'figma-plugin-ds/dist/figma-plugin-ds.css'
```
