### ISSUE TITLE
Build/watch error undefined

### ISSUE THREAD

**Issue by mzilverberg** [yuanqing/create-figma-plugin#49]
Hey,
I would love to use your boilerplate for developing Figma plugins. However, I run into an `undefined` error during the build or watch scripts and can't get it to work. Omitting the last `--yes` parameter does not make a difference. 
I hope you can help me out!

My environment:

- Node: v14.17.4
- NPM: 6.14.14
- Yarn: 1.22.11

Terminal output:
```bash
$ npx --yes -- create-figma-plugin my-plugin
npx: installed 129 in 6.354s
info Scaffolding a new plugin...
? display name My Plugin
? template ui
info Copying "ui" template...
info Installing dependencies...
success Done
$ cd my-plugin
$ yarn run build
yarn run v1.22.11
warning package.json: No license field
$ build-figma-plugin --typecheck --minify
error undefined
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yuanqing** [comment]
Unfortunately I can’t seem to replicate the issue you’re facing. This is my terminal output:

```
$ npx --yes -- create-figma-plugin my-plugin
info Scaffolding a new plugin...
? display name My Plugin
? template ui
info Copying "ui" template...
info Installing dependencies...
success Done
$ cd my-plugin
$ yarn run build
yarn run v1.22.10
warning package.json: No license field
$ build-figma-plugin --typecheck --minify
info Type checking...
success Type checked in 3.138s
info Building...
success Built in 1.100s
✨  Done in 5.05s.
```

**Comment by mzilverberg** [comment]
I was afraid that was the case... Your boilerplate seemed so easy to use, so I was eager to test it out myself! I get the same error on both my iMac and Macbook Pro, unfortunately.
The error itself is not really helpful either, so I'm not sure where to look for the solution. Could it be some generic setup error that causes this, maybe?

**Comment by yuanqing** [comment]
I suspect it could be an issue in the `build-figma-plugin` CLI.

1. It’d help if you can try to identify where exactly the error is occurring. Potentially you could try to add `console.log` statements in the `my-plugin/node_modules/@create-figma-plugin/build/lib/build-async.js` file to trace where the error is being thrown? It looks like the `info Type checking...` line is not being printed in your terminal output, which suggests that the error occurs _before_ this specific line in the `build-async.js` file: https://github.com/yuanqing/create-figma-plugin/blob/78d944331293b0442bf87c41161ec026425e9b70/packages/build/src/build-async.ts#L18

2. Alternatively, you can try to build the entire project locally and symlink to the local copy of the project in your plugin, and then try to debug the source of the error from there. [Instructions are in the README](https://github.com/yuanqing/create-figma-plugin).

I’ll consider adding a `--verbose` flag to the CLI to help with debugging such issues in the future.

**Comment by mzilverberg** [comment]
Ha! Interesting... Your first approach helped me resolve the issue.
I found that the `buildCssModulesTypingsAsync` function returned an error. This caused the `build-async.js` script to jump straight to the catch clause. Fortunately, the error message revealed helpful information for me to successfully fix the issue.

The error was caused by the name of the parent folder, which contained spaces ("Figma plugins/my-plugin"). Renaming that folder resolved the issue.

Thanks a lot for your time and suggestions!

**Comment by mzilverberg** [comment]
PS: A `--verbose` would be a welcome addition ;)

**Comment by yuanqing** [comment]
Great! Glad to know it worked out!

> The error was caused by the name of the parent folder, which contained spaces ("Figma plugins/my-plugin"). Renaming that folder resolved the issue.

Just cut a `1.2.4` release that fixes this specific issue.
