### ISSUE TITLE
Quoting in build-css-modules-typings-async.ts breaks build on windows

### ISSUE THREAD

**Issue by bjj** [yuanqing/create-figma-plugin#51]
The quoting in `exec('${tcm}'...` does not work on Windows. Build works if the single quotes are changed to double quotes.

Further the `reject(error.message)` loses the error and all of the context so all that is printed is `error undefined` (because there is no `error.message`) which makes this hard to track down!

**Comment by yuanqing** [comment]
@bjj Thanks for reporting! Would you like to submit a PR to fix this issue?

**Comment by heybereket** [comment]
Can confirm this, getting the same error.

**Comment by yuanqing** [comment]
This issue should be fixed as of `1.3.2`
