### ISSUE TITLE
Textbox blurs out automatically on every input

### ISSUE THREAD

**Issue by sntiagomoreno** [yuanqing/create-figma-plugin#58]
For some reason when using Textbox inside another component, it will blur out every time I type a single character.

https://user-images.githubusercontent.com/10518268/133860662-c1a3e0b9-bc4e-48d2-afb9-c2c04b2bd182.mp4

**Comment by yuanqing** [comment]
@sntiagomoreno Can you share a *simplified* code example (eg. Gist or GitHub repo) that demonstrates this issue? Unable to replicate or investigate the issue without more information

**Comment by sntiagomoreno** [comment]
Hey my bad! I was creating the component inside the render function. Solved that and now works fine. Thanks!
