### ISSUE TITLE
Any demos how to get all the figma datas to UI?

### ISSUE THREAD

**Issue by weilinzung** [yuanqing/create-figma-plugin#6]
Hi,

I have a hard time to use this boilerplate to render data from the Figma document. Any demos or use cases?

I am able to capture data(all frame names) from a Figma project and with `postMessage` method. And next step I want to render the data on UI with `onmessage = async (event)=> { event.data.message}`, I can console.log the data within the async function, but how do I store the data outside of the async function in order I can use for the returning and rendering to the UI? I know this is a react project, but also with a lot of custom APIs. I want to find out if there is an easy way to do this with `create-figma-plugin`. Thank you!

**Comment by weilinzung** [comment]
**command.js**

```
import { showUI, getSelectedLayersOrAllLayers } from '@create-figma-plugin/utilities';

const layers = await getSelectedLayersOrAllLayers();

showUI({ width: 240, height: 320 }, __html__);
figma.ui.postMessage({ layers  });
```

**ui.js**

```
import { render } from '@create-figma-plugin/ui';
import { test } from './components/test';
export default render(test);
```

**components/test.js**

```
/** @jsx h */
import { h, Fragment } from 'preact';

export function test() {
  let datas;

onmessage = (event) => {
  let { layers } = event.data.pluginMessage;
  datas = layers;
  console.log( layers);
  console.log( datas);
}

  console.log( datas);  // => undified 

  return (
    <Fragment>
      test
      <div>{datas}</div>
    </Fragment>
  )
```

**Comment by yuanqing** [comment]
@weilinzung 

1. Thanks very much for trying this out! Just a note that the docs still needs a bit of work, and that some APIs could still change in the near term – I would recommend depending on the latest exact version (ie. `"0.0.53"`) for all the `@create-figma-plugin/*` modules in your `package.json`.

2. There are several examples of this toolkit in use in [my Figma Plugins](https://github.com/yuanqing/figma-plugins) monorepo. [This particular plugin command](https://github.com/yuanqing/figma-plugins/tree/a30cd2730a2c7a6a17de2f7c558ec0ed60607c40/packages/figma-component-utilities/src/replace-with-component) – part of the [**Component Utilities**](https://www.figma.com/c/plugin/785894722513806497/Component-Utilities) plugin – could be a helpful reference for you.

3. A few quick comments on the code you shared:
    - The command implementation in your `command.js` should be wrapped in an `export default function () { /* ... */ }`.
    - In your `command.js`, the third parameter of `showUI` should be the data that you want to pass to your UI.
    - You would need to convert any Figma objects – your [`layers` is an array of Figma `Node` objects](https://github.com/yuanqing/create-figma-plugin/blob/bbaf6d9151e21f51c35dbad8424d2f297185092b/docs/3-api.md#const-layers--getselectedlayersoralllayers) – into “plain” JavaScript objects before passing the data to `showUI`. (See the example plugin command I shared earlier.)
    - The third parameter that was passed to `showUI` by your command will be received as props in your `components/test.js` component.
    - To send data back-and-forth between your plugin command and UI, you can use [the `addEventListener` and `triggerEvent` APIs](https://github.com/yuanqing/create-figma-plugin/blob/bbaf6d9151e21f51c35dbad8424d2f297185092b/docs/3-api.md#events). (Again, see the example plugin command I shared earlier.)

Hope this helps!

**Comment by weilinzung** [comment]
@yuanqing That would help a lot, thanks for explaining.

For the `showUI`, is only two parameters available? option and data. Not sure if I am right?
`showUI({ width: 240, height: 320 }, __html__);` -> `showUI({ width: 240, height: 320 }, __html__, [datas]);`

**Comment by yuanqing** [comment]
Ah, you’re right – `showUI` only takes 2 parameters, and `data` is the second not third parameter

**Comment by weilinzung** [comment]
@yuanqing much clear now. thanks so much!
