### ISSUE TITLE
How do I dynamically use an icon in the Layer component?

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#66]
Hi there! I'm struggling to understand out how to pass an icon name into the icon attribute of the Layer component. I have an object that has a key in which the value is a string that represents the icon component to use.

**Code**:

![image](https://user-images.githubusercontent.com/11559173/137964251-b1311f56-02f9-4417-a493-69003a6b0280.png)

**Output** (Note: the rendered result is above the inspect window, and as you can see it is just showing the string and not the rendered component):

![image](https://user-images.githubusercontent.com/11559173/137963828-f97067ab-4296-4de9-a8b8-a6cd4350d006.png)

**Comment by yuanqing** [comment]
```tsx
import { h } from 'preact'

// ...
icon={h(token.layerIcon, {})}
```

**Comment by Jeremy-Knudsen** [comment]
Okay! I did a quick test and this worked!

![image](https://user-images.githubusercontent.com/11559173/138330367-6b6aa2ac-650c-4f26-aa4c-21b793b04881.png)

![image](https://user-images.githubusercontent.com/11559173/138330503-4a5ce659-7772-43aa-9867-085387c2063f.png)
