### ISSUE TITLE
Utility function to determine the visibility of a nested node by looping through its parent(s) to check if all are visible

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#68]
A helpful utility function that could be added would be one to determine whether a node is _truly_ visible on the canvas or not. The fact that a nested node can actually be invisible on the canvas even if its visible attribute is true makes such a utility function so convenient. You really don't know a node's visible status, unless you loop through its parent(s) to check visible for each parent node.

![image](https://user-images.githubusercontent.com/11559173/138773700-1f1266cb-f882-4efe-bc97-7248d8b6950c.png)

I'm thinking something like this... 
![image](https://user-images.githubusercontent.com/11559173/138786905-9414f7fd-0b6f-4f0c-870d-96835135fa3a.png)

**Comment by saeedalipoor** [comment]
I opened a PR for that [#75]

**Comment by yuanqing** [comment]
Shipped in `1.8.0`
