### ISSUE TITLE
tcm package is not specified as a dependency

### ISSUE THREAD

**Issue by svallory** [yuanqing/create-figma-plugin#69]
Th `tcm` package is being used in [`buildCssModulesTypingsAsync()`](https://github.com/yuanqing/create-figma-plugin/blob/692c51a0f850b6a36ddde1f22e2e21c4128e5d32/packages/build/src/utilities/build-css-modules-typings-async.ts#L6) but I couldn't find any reference to it.

Also, I'm wondering why use "find-up" instead of `require`

**Comment by yuanqing** [comment]
1. `tcm` is the CLI included in the `typed-css-modules` package
2. You can’t use require because we need the _path_ to the binary so that we can run it using `exec`

**Comment by svallory** [comment]
got it, thanks!
