### ISSUE TITLE
TextboxNumeric problem with incrementSmall = 0.1

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#70]
I'm encountering an issue with using a value less than 0.5 for the incrementSmall property in TextboxNumeric. As soon as I put this back to 0.5 the component works as expected with keyboard input (up and down arrows).

![image](https://user-images.githubusercontent.com/11559173/139494889-08079ebf-dbf9-4669-8083-c007d1fb2631.png)

**Comment by yuanqing** [comment]
This should be fixed in the next release

**Comment by yuanqing** [comment]
Fixed as of `1.7.0`
