### ISSUE TITLE
Figma's new flag figma.skipinvisiblechildren is not supported

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#78]
See Figma API reference:
https://www.figma.com/plugin-docs/api/properties/figma-skipinvisibleinstancechildren/

I keep getting an error when trying to set `figma.skipinvisiblechildren = true`

**Comment by yuanqing** [comment]
Check if you have the correct version of `@figma/plugin-typings` Installed

**Comment by Jeremy-Knudsen** [comment]
I did a fresh install. Does it work for you?

**Comment by yuanqing** [comment]
`create-figma-plugin` will always install a specific version of Figma typings (ie. `@figma/plugin-typings` or `@figma/widget-typings`) that is known to be compatible with the Create Figma Plugin toolkit. However, you should be able to manually change the typings versions in your `package.json` if you want to.

Using `1.41.1` of `@figma/plugin-typings` seems to solve the issue you raised

**Comment by Jeremy-Knudsen** [comment]
Thanks, that makes sense.
