### ISSUE TITLE
css file can't be parsed by css-loader because of invalid `@import: url()` statement 

### ISSUE THREAD

**Issue by felixhaeberle** [yuanqing/create-figma-plugin#82]
Hey, I get the following error when using the Dropdown component:

```
ERROR in ./node_modules/@create-figma-plugin/ui/lib/css/base.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url('https://fonts.googleapis.com/css?family=Inter:400,600&display=swap');
| 
| :root {
 @ ./node_modules/@create-figma-plugin/ui/lib/utilities/render.js 1:0-26
 @ ./node_modules/@create-figma-plugin/ui/lib/index.js
 @ ./src/app/components/studio/Toolbar/DropdownPlain/DropdownPlain.tsx
 @ ./src/app/components/App.tsx
 @ ./src/app/index.tsx
```

My webpack configuration is perfectly fine to parse this `base.css` file, but unfortunately, the `@import: url()` can't be handled properly.

webpack config
```
...
      {
        test: /\.css$/,
        loaders: ['style-loader', 'css-loader']
      }
...
```

**Comment by felixhaeberle** [comment]
Why to remove the @import and use a <link> tag instead:
https://stackoverflow.com/a/12380004/6854385

**Comment by yuanqing** [comment]
Unfortunately use of the `@create-figms-plugin/ui` package with Webpack is not officially supported at the moment. All components will work out-of-the-box if you use the `build-figma-plugin` CLI (see the docs)

**Comment by felixhaeberle** [comment]
Thanks for you quick answer, appreciate it very much!! :) 
Is there any possibility to move the `@import` statement out of the base.css? 
Although it's not best practice, it can't be parsed by webpack in this way. 
Everything except of this tiny line is working perfectly.
Thank you!!

**Comment by yuanqing** [comment]
Looking at the Webpack CSS loader docs, it should be able to handle `@import` statements in CSS…?

https://webpack.js.org/loaders/css-loader/#import

**Comment by felixhaeberle** [comment]
With the suggested configuration, I get the following:

```
ERROR in ./node_modules/@create-figma-plugin/ui/lib/css/base.css 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url('https://fonts.googleapis.com/css?family=Inter:400,600&display=swap');
| 
| :root {
 @ ./node_modules/@create-figma-plugin/ui/lib/utilities/render.js 1:0-26
 @ ./node_modules/@create-figma-plugin/ui/lib/index.js 222:0-47 222:0-47
 @ ./src/app/components/studio/Toolbar/DropdownPlain/DropdownPlain.tsx 2:0-51 18:31-39
 @ ./src/app/components/App.tsx 8:0-73 60:56-69
 @ ./src/app/index.tsx 3:0-35 5:36-39
```
