### ISSUE TITLE
Enhancement: add 'none' as an option for the space attribute for <Stack>

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#83]
Easily editable, but it would make sense to offer the `space='none'` option out of the box, which is especially useful for `<Stack>`

**Comment by yuanqing** [comment]
I think a Stack without space is achievable without actually using the `Stack` component

---

With space:

```tsx
<Stack space="small">
  <div>foo</div>
  <div>bar</div>
  <div>baz</div>
</Stack>
```

Without space:

```tsx
import { Fragment } from 'preact'

// ...

<Fragment>
  <div>foo</div>
  <div>bar</div>
  <div>baz</div>
</Fragment>
```
