### ISSUE TITLE
@create-figma-plugin/build doesn't work inside a pnpm workspace

### ISSUE THREAD

**Issue by gluck** [yuanqing/create-figma-plugin#84]
When the plugin is part of a pnpm monorepo (using workspaces), it fails to find `tcm`.

Reason is that in that case `tcm` is present only in:
`node_modules/@create-figma-plugin/build/node_modules/.bin/`

And not in:
`node_modules/.bin/`

Fix:
- use `{ cwd: __dirname }` as `findUp` option (default is `process.cwd()`)

Workaround:
- install `typed-css-modules` in figma plugin so `tcm` binary gets installed in `node_modules/.bin` as well.

**Comment by yuanqing** [comment]
@gluck Can you confirm whether this issue is fixed by `@create-figma-plugin/build@1.8.4-alpha.0`?

**Comment by yuanqing** [comment]
The commit that should fix this issue is https://github.com/yuanqing/create-figma-plugin/commit/96d1025256b43d71e0709393ebedf186bc64df23

**Comment by gluck** [comment]
I haven't tested yet but afaict it won't fix it, this folder will only exist in cwd if the user installed it.

**Comment by yuanqing** [comment]
Got it. Just to check, is the repo set up that such that `@create-figma-plugin/build` is a root dependency only – ie. it is specified in `./package.json` but not in `./packages/my-plugin/package.json`?

**Comment by gluck** [comment]
The other way around.
But if you think about it, tcm being a node dependency, it should resolve it like node does, i.e. crawling folders up starting from __dirname.
Thinking about it, using require.resolve('...') (and finding the binary from there) should also work

**Comment by yuanqing** [comment]
Verified that this is fixed as of `1.8.4`

**Comment by gluck** [comment]
Confirmed working on my side too, thx !
