### ISSUE TITLE
Issue: Modal content not scrollable

### ISSUE THREAD

**Issue by Jeremy-Knudsen** [yuanqing/create-figma-plugin#85]
I'm using a `Modal` that appears from the right side and populating it with a list of items, but when the list gets too long the list is unable to scroll, no matter if I set the overflow style to scroll.

**Comment by Jeremy-Knudsen** [comment]
I figured out a workaround using min-content.

Reference: https://stackoverflow.com/questions/21515042/scrolling-a-flexbox-with-overflowing-content#:~:text=Basically%2C%20to%20make%20a%20flexbox%20cell%20scrollable%2C%20you,instead.%20Share%20answered%20Feb%2024%20%2716%20at%2018%3A20

**Comment by Jeremy-Knudsen** [comment]
I did have to add the `overflow: auto` css attribute to `.modal` in `modal.css` ...
<img width="263" alt="image" src="https://user-images.githubusercontent.com/11559173/153489781-10b15bf9-2426-4b6f-b998-6f083d545563.png">

**Comment by Jeremy-Knudsen** [comment]
And lastly, to make the header sticky at the top with the content scrolling underneath:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/11559173/153491721-d89eed89-357b-43bb-9af9-7db22eee6761.png">

**Comment by yuanqing** [comment]
What I do is to set a `max-height` on the inner `div` element:

```tsx
<Modal {/* ...modal props... */}>
  <div class={styles.content}>
    {/* content */}
  </div>
</Modal>
```

```css
.content {
  max-height: 320px;
  overflow-y: auto;
}
```

**Comment by Jeremy-Knudsen** [comment]
Thanks yuanqing!
