### ISSUE TITLE
Question: Tabs (very dumb question)

### ISSUE THREAD

**Issue by pwichmann** [yuanqing/create-figma-plugin#87]
Many thanks for this amazing tool!

I was able quickly create a mockup of a plugin I want to develop.
The only component I am too dumb to use is the Tabs component. How do I need to declare the Tabs in JSX, so that they work?
I would just need the simplest working example.

I tried:
```HTML
        <Tabs onChange={handleCreateRectanglesButtonClick} options={[]} value="foo">
        </Tabs>
```

I tried:
```HTML
        <Tabs>
              <TabsOption>Tab1</TabsOption>
              <TabsOption>Tab2</TabsOption>
        </Tabs>
```

Sorry for this very dumb question. I am a TypeScript / React / Preact / JSX noobie -- combing from a Python background.

**Comment by yuanqing** [comment]
Does the example in the Storybook work for you? https://yuanqing.github.io/create-figma-plugin/storybook/?path=/story/components-tabs--selected

**Comment by pwichmann** [comment]
I think I got it now!
