### ISSUE TITLE
Question: adding the UI library to an existing ReactJS plugin

### ISSUE THREAD

**Issue by Juarrow** [yuanqing/create-figma-plugin#88]
I'm pretty new to ReactJS and Webpack so pardon me.

How to use @create-figma-plugin/ui in an existing ReactJS plugin?
Can this be done without using build-figma-plugin and how to change my webpack configuration file?

**Comment by yuanqing** [comment]
@Juarrow – This use case is not officially supported at the moment. I’d recommend using a different UI library that’s made specifically using React eg. https://github.com/alexandrtovmach/react-figma-plugin-ds

**Comment by Juarrow** [comment]
Thanks for the quick answer. I'll have a look.
