### ISSUE TITLE
Error when running build or watch

### ISSUE THREAD

**Issue by Juarrow** [yuanqing/create-figma-plugin#96]
![image](https://user-images.githubusercontent.com/5290648/161614512-ffcd79c5-7e28-48fa-8647-1fa91d4f2f53.png)

I wonder, why does it try to run in windows script host instead of within it's node environment?
(I only have this issue with the create-figma-plugin created build/run commands. Other frameworks's JS CLIs work fine.,)

Why does this even try to execute js files like this?

**Comment by fwextensions** [comment]
It seems to try to execute or open that file for some reason.  I opened [this bug](https://github.com/yuanqing/create-figma-plugin/issues/93) because every time I run the script, it opens that `cli.js` file in Webstorm and triggers the creation of a new project.  It's definitely doing something with that file that isn't cross-platform compatible.

**Comment by Juarrow** [comment]
@fwextensions the thing is, that it does not even start to watch or anything when this happens. So i cannot use the CLI without looking for a workaround.

**Comment by Juarrow** [comment]
So... it launches a console in headless mode with some arguments i don't know. 
![image](https://user-images.githubusercontent.com/5290648/162055181-8c18b442-2263-4020-9051-35fb9a144775.png)


I guess it's for watching for file changes.

But when i quit using CTRL+C, then this process stays open.

Sorry, but I find this suspicious.

**Comment by fwextensions** [comment]
I'm running it on Windows 11, usually in the Webstorm terminal, which is loading PowerShell.  Maybe try running it in PowerShell or Windows Terminal instead of a cmd shell?  (Though for me, a cmd shell seems to show the same behavior as PS.)

**Comment by Juarrow** [comment]
I did that using cmd and bash. Same result. When i allow running it with Node.Js i get this undying conhost process (but then it works).

**Comment by Juarrow** [comment]
Guess it comes from those:
https://github.com/yuanqing/create-figma-plugin/blob/8b63d7bb9a12351d4d3a43ab7b9085e62f7e9f43/packages/build/src/utilities/build-css-modules-typings-async.ts#L18-L25

**Comment by fwextensions** [comment]
Nice.  I think the way that `exec()` call is getting created assumes executing a `.js` file will run it in Node, but it'll depend on how your Windows system is set up.  For me, it seems to pass each of those strings as arguments to Webstorm, so it opens the `cli.js` file, but then just sees `src`, which I think it interprets as a folder path relative to the app.  So it just opens a new project called `src` inside the app directory, which explains why it doesn't have any of my source files in it.  

On your system, it looks like the default Web Script Host is handling JS files and is erroring on the first `import` statement, which it's far too old to understand.

I haven't tried using any CSS modules with this script, but I'm guessing from this behavior that it won't work at all on Windows.

**Comment by yuanqing** [comment]
Is the fix here to add a `node` prefix to that `exec` call – have something like `node "${tcm}" ${constants.build.srcDirectoryName}` instead?

**Comment by fwextensions** [comment]
Probably?  That assumes the path to the node executable is set up correctly, which is probably reasonable.  I've never tried to build a cross-platform node CLI, though.

**Comment by yuanqing** [comment]
I’m open to merge a PR with this fix if you’re able to verify that it works on Windows. (I don’t have access to a Windows machine.) Instructions to test on your local plugin are in the project README

**Comment by Juarrow** [comment]
@yuanqing Nice! 

One question though. Do you need to spawn the CLI like this? Wouldn't it be possible to use worker threads, if you need to run this in parallel to some other code?

**Comment by MikeWilson** [comment]
@Juarrow I ran into this error after upgrading to Windows 11. I fixed it by:

1. Opening File Explorer and finding a Javascript file
2. Right click the file and open the properties
3. Set the default 'Opens with' to Node

**Comment by Juarrow** [comment]
@MikeWilson thanks. I'm already using it half-way like this, by always doing it manually. I don't want JS-files to be automatically executed with Node. Security, Paranoia and all that stuff^^

**Comment by yuanqing** [comment]
This should be fixed in `1.9.1`
