### ISSUE TITLE
Dropdown Component: Hidden menu div can exceed with dimensions of the plugin window causing scrollbars to appear unintentionally

### ISSUE THREAD

**Issue by aashreys** [yuanqing/create-figma-plugin#97]
I'm placing two Dropdown components side-by-side in a div flexbox and the hidden menu component on the rightmost dropdown is exceeding the bounds of the window causing a horizontal scrollbar, as shown in the picture below.

![Screen Shot 2022-04-24 at 12 20 23 PM](https://user-images.githubusercontent.com/6137765/164986720-86a04e1e-0ce2-4699-bb0e-b30ccff247cf.png)

If I reduce the width of the hidden menu through developer tools, the scrollbar disappears once the menu fits the plugin window dimensions.

**Comment by aashreys** [comment]
Curious how I can set up a local development version of Create Figma Plugin and test changes to fix this? If I make progress, happy to contribute directly with a PR.

**Comment by yuanqing** [comment]
There’s a script to symlink to the local copy of Create Figma Plugin from your plugin. Instructions are in the README: https://github.com/yuanqing/create-figma-plugin/blob/8b63d7bb9a12351d4d3a43ab7b9085e62f7e9f43/README.md#contributing

**Comment by aashreys** [comment]
Upon further investigation, I've found that the same issue causes vertical scrollbars to appear if a dropdown is the last element in a vertical UI stack. 
![image](https://user-images.githubusercontent.com/6137765/165882721-eb55a86c-64c8-4bfb-9d3b-5bb7bcc9f46a.png)

**Comment by yuanqing** [comment]
@aashreys – The fix for this bug is currently on the `next` branch, and will be included in the next release. (In the meantime, if you can help to test the changes locally in your plugin, that would be awesome!)

**Comment by aashreys** [comment]
Tested locally. Still seeing the scrollbars and now a new bug where the dropdown menu jumps around as I move the cursor over it. Attached a video.

https://user-images.githubusercontent.com/6137765/166626336-520f14ce-c0d4-4b7e-8a21-be5d4b31c59f.mp4

Thanks for looking into this!

**Comment by yuanqing** [comment]
Fixed in `1.9.1`
