### ISSUE TITLE
Add a dark mode theme to `@create-figma-plugin/ui`

### ISSUE THREAD

**Issue by yuanqing** [yuanqing/create-figma-plugin#99]
Will likely involve a major version bump

**Comment by yuanqing** [comment]
https://www.figma.com/plugin-docs/css-variables/

Current plan:
- Deprecate all the color variables in [`packages/ui/src/css/base.css`](https://github.com/yuanqing/create-figma-plugin/blob/510d5375dff0cc291e4d3d973ffaedf6fe21e8f5/packages/ui/src/css/base.css)
- The `themeColors` option will default to `true` in the [`showUI`](https://github.com/yuanqing/create-figma-plugin/blob/510d5375dff0cc291e4d3d973ffaedf6fe21e8f5/packages/utilities/src/ui.ts) utility
- Use the CSS variables provided by Figma in all UI component styles

**Comment by abynim** [comment]
Refreshing this page three times a day 😅

**Comment by yuanqing** [comment]
- [x] Banner
- [x] Button
- [x] Checkbox
- [x] Columns
- [x] Container
- [x] Disclosure
- [x] Divider
- [ ] Dropdown
- [x] File Upload Button
- [x] File Upload Dropzone
- [ ] Icon
- [x] Icon Toggle Button
- [x] Inline
- [ ] Layer
- [ ] Loading Indicator
- [x] Middle Align
- [ ] Modal
- [x] Preview
- [x] Radio Buttons
- [x] Search Textbox
- [x] Segmented Control
- [ ] Selectable Item
- [x] Stack
- [x] Tabs
- [x] Text
- [ ] Textbox
- [ ] Textbox Autocomplete
- [ ] Textbox Color
- [ ] Textbox Multiline
- [ ] Textbox Numeric
- [x] Toggle
- [x] Vertical Space

**Comment by yuanqing** [comment]
@romannurik Feel free to try out the branch named `next-v2` and run the Storybook

**Note that `v2` will involve breaking changes to various component APIs.** TypeScript _should_ catch most of the breaking changes, but I’ll be making a detailed migration guide to help people migrate over

**Comment by romannurik** [comment]
Just tried to give it a go, was getting some JS errors due to Preact hooks for some reason with the `next-v2` branch (I may not have set it up correctly) so giving up for now. Eager to try out the new version when it's ready!

**Comment by yuanqing** [comment]
I’ll share more here when things are more stable and more ready for testing! :+1:

**Comment by yuanqing** [comment]
https://user-images.githubusercontent.com/3170842/170748837-695882c2-7562-49a7-a159-7d6e4d39d684.mp4

**Comment by romannurik** [comment]
@yuanqing the `symlink.sh` command got that fixed! The only remaining issue was that Figma wasn't injecting the CSS vars, and `themeColors: true` wasn't automatically being passed to Figma's `showUI` (and create-figma-plugin's `showUI` method didn't accept `themeColors`, so I just disabled type-checking temporarily to get it working.

But anyway, yes I'm looking forward to testing more once things are more stable.

Kudos btw on such an amazing library, toolchain, etc. 👏🏻 👏🏻 👏🏻

**Comment by yuanqing** [comment]
FYI – Will be publishing a `v2.0.0-alpha.0` to npm soon (https://github.com/yuanqing/create-figma-plugin/pull/106)

**Comment by yuanqing** [comment]
`2.0.0-alpha.0` is now available on npm. Update all `@create-figma-plugin/*` versions in your `package.json` to `2.0.0-alpha.0`.

There are significant breaking component API changes in v2 – see [the detailed changelog](https://github.com/yuanqing/create-figma-plugin/blob/main/CHANGELOG.md#create-figma-pluginui200). Most of the code changes that are required to migrate to v2 should be surfaced via TypeScript.

**Comment by romannurik** [comment]
Can't wait to give it a try, thanks!!

**Comment by romannurik** [comment]
Tested — all works great and as expected!

**Comment by yuanqing** [comment]
🚀 https://twitter.com/yuanqinglim/status/1534902408026828800
